### ISSUE TITLE
PluginManager) OnAllPluginsLoaded failed

### ISSUE THREAD

**Issue by pubzoneweb** [daffyyyy/CS2-SimpleAdmin#159]
![2](https://github.com/user-attachments/assets/da035215-cc38-4c0e-8cf1-062237d3671c)

EROR] (cssharp:PluginManager) OnAllPluginsLoaded failed
System.Collections.Generic.KeyNotFoundException: The given key 'menu:nfcore' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at CounterStrikeSharp.API.Core.Capabilities.PluginCapability`1.Get() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Capabilities/PluginCapability.cs:line 17
   at **CS2_SimpleAdmin.CS2_SimpleAdmin.OnAllPluginsLoaded(Boolean hotReload)** in /home/runner/work/CS2-SimpleAdmin/CS2-SimpleAdmin/CS2-SimpleAdmin/CS2-SimpleAdmin.cs:line 61
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 106

**After the latest update, I updated Metamod and CounterStrike Sharp. All plugins are working perfectly, except for CS2-SimpleAdmin, which is not functioning**

**Comment by pubzoneweb** [comment]
The issue was resolved; I didn't have the following installed:

PlayerSettings - Required by MenuManagerCS2
AnyBaseLibCS2 - Required by PlayerSettings
MenuManagerCS2
