### ISSUE TITLE
[BUG] Error log

### ISSUE THREAD

**Issue by skaen** [daffyyyy/CS2-SimpleAdmin#19]
```
2023-12-25 16:41:06.783 +03:00 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: The given key '76561198055403892' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at CS2_SimpleAdmin.CS2_SimpleAdmin.<>c__DisplayClass66_0.<OnClientAuthorized>b__3() in /home/runner/work/CS2-SimpleAdmin/CS2-SimpleAdmin/Events.cs:line 229
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82
```

Current API Version: 125
Metamod:Source version 2.0.0-dev+1275

**Comment by daffyyyy** [comment]
Temp fixed im latest version
