### ISSUE TITLE
CS2-SimpleAdmin.json not found

### ISSUE THREAD

**Issue by mayersgamer** [daffyyyy/CS2-SimpleAdmin#25]
addons/counterstrikesharp/configs/plugins/CS2-SimpleAdmin/CS2-SimpleAdmin.json

not created how configure admin if this file doesnt exist

**Comment by criskkky** [comment]
Same problem here

**Comment by daffyyyy** [comment]
Check logs for errors

**Comment by criskkky** [comment]
> @daffyyyy: Check logs for errors

1. I uploaded entire `CS2-SimpleAdmin (build v55)` folder in `/game/csgo/addons/counterstrikesharp/plugins`
2. I started my server to generate `SimpleAdmin.json` (wasn't created by plugin)
3. I restarted my server in case that could be a solution (same problem, file isn't created)

4. Logs
``` txt
17:54:47 [EROR] (cssharp:PluginManager) Failed to load plugin from /home/container/game/csgo/addons/counterstrikesharp/plugins/CS2-SimpleAdmin/CS2-SimpleAdmin.dll
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Exception: [CS2-SimpleAdmin] You need to setup Database credentials in config!
   at CS2_SimpleAdmin.CS2_SimpleAdmin.OnConfigParsed(CS2_SimpleAdminConfig config) in /home/runner/work/CS2-SimpleAdmin/CS2-SimpleAdmin/CS2-SimpleAdmin.cs:line 53
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at CounterStrikeSharp.API.Core.BasePlugin.InitializeConfig(Object instance, Type pluginType) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/BasePlugin.cs:line 419
   at CounterStrikeSharp.API.Core.Plugin.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 200
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 52
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 34```

**Comment by criskkky** [comment]
@daffyyyy Json file appeared, maybe was some problem with my VPS provider.
@mayersgamer make sure you are in `/game/csgo/addons/counterstrikesharp/configs/plugins/CS2-SimpleAdmin` and then edit .json file with your database info.

**Comment by mayersgamer** [comment]
> @daffyyyy Json file appeared, maybe was some problem with my VPS provider. @mayersgamer make sure you are in `/game/csgo/addons/counterstrikesharp/configs/plugins/CS2-SimpleAdmin` and then edit .json file with your database info.

nothing yet , im used to plugins creating json files once i restart server but in this case its not.

**Comment by mayersgamer** [comment]
![Uploading Screenshot_2024-01-07-07-39-05-66_40deb401b9ffe8e1df2f1cc5ba480b12.jpg…]()

**Comment by mayersgamer** [comment]
![Screenshot_2024-01-07-07-39-05-66_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/daffyyyy/CS2-SimpleAdmin/assets/5068539/f459dfbd-8d8b-41a6-801c-96323bb31071)

as you can see

**Comment by daffyyyy** [comment]
Not plugin issue, check css version/logs to find what cause problem.
