### ISSUE TITLE
[BUG] chat phrases doesn't appear. (Build 58)

### ISSUE THREAD

**Issue by criskkky** [daffyyyy/CS2-SimpleAdmin#28]
I'm getting this error log in Build 58 and chat phrases doesn't appear.
```txt
16:45:42 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at CS2_SimpleAdmin.CS2_SimpleAdmin.<>c__DisplayClass45_0.<OnSlapCommand>b__1(CCSPlayerController player) in /home/runner/work/CS2-SimpleAdmin/CS2-SimpleAdmin/CS2-SimpleAdmin.cs:line 1342
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at CS2_SimpleAdmin.CS2_SimpleAdmin.OnSlapCommand(CCSPlayerController caller, CommandInfo command) in /home/runner/work/CS2-SimpleAdmin/CS2-SimpleAdmin/CS2-SimpleAdmin.cs:line 1339
   at CounterStrikeSharp.API.Core.BasePlugin.<>c__DisplayClass41_0.<AddCommand>b__0(Int32 i, IntPtr ptr) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/BasePlugin.cs:line 259
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82
```
For now I returned to Build 57 and it's ok.

**Comment by daffyyyy** [comment]
What language are you using on the server?

**Comment by criskkky** [comment]
Tried just with "EN" and "ES"

**Comment by daffyyyy** [comment]
Please use latest build 🤪

**Comment by criskkky** [comment]
I'll test it :p

**Comment by criskkky** [comment]
Fixed
