### ISSUE TITLE
[BUG] Dont Change Map Or Workshop Map

### ISSUE THREAD

**Issue by t4r1k58** [daffyyyy/CS2-SimpleAdmin#69]
i Update My Server But, After update css_map and css_wsmap command don't work.

**Comment by radouee** [comment]
it does work for me

**Comment by sazarkin** [comment]
I am getting this error on `!map de_dust2` command
```L 03/15/2024 - 10:37:310:38:39 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at CS2_SimpleAdmin.CS2_SimpleAdmin.ChangeMap(CCSPlayerController caller, String map, CommandInfo command) in /home/runner/work/CS2-SimpleAdmin/CS2-SimpleAdmin/Commands/basecommands.cs:line 513
   at CS2_SimpleAdmin.CS2_SimpleAdmin.OnMapCommand(CCSPlayerController caller, CommandInfo command) in /home/runner/work/CS2-SimpleAdmin/CS2-SimpleAdmin/Commands/basecommands.cs:line 457
   at CounterStrikeSharp.API.Core.Commands.CommandManager.HandleCommandInternal(Int32 playerSlot, IntPtr commandInfo) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Commands/CommandManager.cs:line 159
   at InvokeStub_Action`2.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 120```

**Comment by daffyyyy** [comment]
Fixed
